### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by emamalias** [emamalias/experimental-bb-marketing-pages#2]
# Implement home page 

## todo block components

- [ ] Header (brand, Navlinks, actions)
- [ ] Hero [default]
- [ ] Logo cloud
- [ ] Image
- [ ] How it works / Feature
- [ ] Hero [variant2]
- [ ] FeatureAccordion 
- [ ] Hero [variant3]
- [ ] FeatureGrid
- [ ] Hero [variant4]
- [ ] CTA

## todo reusable components

- [ ] Title (color)
- [ ] Card (img, heading, body, footer)
- [ ] Navlinks
- [ ] Brand (logo, name)
